detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  UnusedPrivateMethod:
    enabled: true

directories:
  "app/views":
    TooManyStatements:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false

exclude_paths:
  - vendor
