detectors:
  IrresponsibleModule:
    enabled: false

directories:
  "app/views":
    TooManyStatements:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false

exclude_paths:
  - vendor
